version: '3'

tasks:
  default:
    cmds:
      - task -l
      - go fmt ./...
    silent: true

  run:
    desc: runs the server 
    cmds:
      - go run app.go icons.go experience.go
      


  open:
    desc: opens the lint
    cmds:
      - google-chrome --profile-directory "http://localhost:8080"

  docker-b:
    desc: build docker image with the latest code
    cmds:
      - docker build -t my-cv:latest .
      - task:  docker-cleanse

  docker-r:
    desc: runs docker image with the latest changes
    cmds:
      - docker run -p 8080:8080  my-cv:latest &

  docker-cleanse:
    desc: removes dangling images
    cmds:
      - docker image prune --filter "dangling=true"

  check-pid:
    desc: opens the lint
    cmds:
      - lsof -i :8080
      - echo "now kill pid of the app running on this port"
