version: '3'

tasks:
  default:
    cmds:
      - task -l
      - go fmt ./...
    silent: true

  run:
    desc: runs the server 
    cmds:
      - go run app.go icons.go experience.go
      


  open:
    desc: opens the lint
    cmds:
      - google-chrome --profile-directory "http://localhost:8080"

  check-pid:
    desc: opens the lint
    cmds:
      - lsof -i :8080
      - echo "now kill pid of the app running on this port"
